name: Format
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          components: rustfmt
      - uses: actions/checkout@master
      - name: Check format
        run: cargo fmt --all -- --check