name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo check --verbose --all --all-features
    - name: Run tests
      run: cargo test --verbose --all --all-features
